### ISSUE TITLE
Taxis despawn but roads are connected

### ISSUE THREAD

**Issue by SubaruSVX** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#361]
### Description
I don't know if there are any others that have this issue, but when I have taxis driving around my city, when they get close to their destination to pick up a passenger, they despawn. Sometimes, I see a "Confused" on what they are doing before that, but it's been really inconsistent.

### Reproduction Steps
Add more steps as nessecary.
1. Build a taxi depot
2. Have enough demand 
3. Watch

### Mod List
Please list the mods enabled when you noticed the bug.
Hard Mode (ID=18446744073709551615)                         deactivated
Unlimited Money (ID=18446744073709551615)                   activated
Unlimited Oil And Ore (ID=18446744073709551615)             activated
Unlimited Soil (ID=18446744073709551615)                    activated
Unlock All (ID=18446744073709551615)                        deactivated
Employ Overeducated Workers V2 (ID=1674732053)              activated
Network Skins (ID=543722850)                                activated
Prop Snapping (ID=787611845)                                activated
Los Santos Rock Radio (ID=1564632871)                       activated
Metro Overhaul (ID=816260433)                               activated
Train Converter (ID=795514116)                              activated
Prefab Hook (ID=530771650)                                  activated
Advanced Stop Selection (ID=1394468624)                     activated
Non Stop Pop FM (ID=1563236161)                             activated
Ambient Sounds Tuner (ID=818641631)                         activated
Rebalanced Industries (ID=1562650024)                       activated
Tiny Segments 2.0 (ID=1586027591)                           activated
Plop The Growables (ID=924884948)                           activated
BigCity (ID=1270675750)                                     activated
Vehicle Wealthizer 1 (ID=1633580257)                        deactivated
Klyte Commons 1.1.6 (ID=1312735149)                         deactivated
First Person Camera (ID=650805785)                          activated
CSL Music Mod (ID=422934383)                                activated
Pollution Solution (ID=1263262833)                          activated
Airport Roads 1.3.7 (ID=465127441)                          activated
Unlock All + Wonders & Landmarks (ID=458519223)             activated
Better bulldoze Tool (ID=417965096)                         activated
Surface Painter (ID=689937287)                              activated
Automatic Bulldoze v2 (ID=639486063)                        activated
Find It! 1.5.4 (ID=837734529)                               activated
Network Extensions 2 (ID=812125426)                         activated
Prop & Tree Anarchy (ID=593588108)                          activated
Extra Landscaping Tools (ID=502750307)                      activated
Fine Road Anarchy 1.3.5 (ID=802066100)                      activated
Fine Road Tool 1.3.7 (ID=651322972)                         activated
Precision Engineering (ID=445589127)                        activated
More Effective Transfer Manager (ID=1680840913)             activated
Favorite Cims v0.3.1b (ID=426460372)                        activated
Move It 2.4.1 (ID=1619685021)                               activated
No Park Building Fires (ID=1718245521)                      activated
AST: KRA Sound Pack (ID=618536610)                          activated
TM:PE 10.20 (ID=1637663252)                                 activated
Empty It! (ID=1661072176)                                   activated
Achieve It! (ID=1567569285)                                 activated
Real Time (ID=1420955187)                                   activated
Advanced Vehicle Options 1.8.5 (ID=1548831935)              activated
Cargo Hold Fix (ID=1721492498)                              activated
WG Citizen Lifecycle Rebalance v2.6 (ID=654707599)          activated
WG Realistic Population v8.4.0 (ID=426163185)               activated
Show It! (ID=1556715327)                                    activated
Hide It! (ID=1591417160)                                    activated
Service Vehicle Selector 2 (r4.0.2) (ID=934994075)          activated
Improved Public Transport 2 [r4.3.1] (ID=928128676)         activated
Loading Screen Mod (ID=667342976)                           activated

### Output Log

[Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3267877/Player.log)

### Savegame (Optional)

https://steamcommunity.com/sharedfiles/filedetails/?id=1736078702

### Additional Info
Might not have to do with TM:PE, but I'm placing this here if it is.

**Comment by VictorPhilipp** [comment]
Possible causes:

- Vehicle restrictions are in place: Taxis are unable to find a path to the next pick-up point.
- Traffic jams: When there are too many traffic jams along the route path-finding costs can explode which eventually make path-finding fail

**Comment by VictorPhilipp** [comment]
The segment grid in this savegame is corrupted:

```
Invalid list detected!
   at System.Environment.get_StackTrace()
   at PathManager.FindPathPosition(Vector3 position, Service service, Service service2, LaneType laneType, VehicleType vehicleType, VehicleType stopType, Boolean allowUnderground, Boolean requireConnect, Single maxDistance, Position ByRef pathPosA, Position ByRef pathPosB, Single ByRef distanceSqrA, Single ByRef distanceSqrB)
   at PathManager.FindPathPosition(Vector3 position, Service service, LaneType laneType, VehicleType vehicleType, Boolean allowUnderground, Boolean requireConnect, Single maxDistance, Position ByRef pathPos)
   at PassengerCarAI.FindParkingSpaceRoadSide(UInt16 ignoreParked, UInt16 requireSegment, Vector3 refPos, Single width, Single length, Vector3 ByRef parkPos, Quaternion ByRef parkRot, Single ByRef parkOffset)
   at TrafficManager.Manager.Impl.AdvancedParkingManager+<>c__DisplayClass22_0.<FindParkingSpaceAtRoadSide>b__0(Int32 i, Int32 j)
   at TrafficManager.Util.LoopUtil+<>c__DisplayClass1_0.<SpiralLoop>b__0(Int32 x, Int32 y)
   at TrafficManager.Util.LoopUtil.SpiralLoop(Int32 width, Int32 height, TrafficManager.Util.TwoDimLoopHandler handler)
   at TrafficManager.Util.LoopUtil.SpiralLoop(Int32 xCenter, Int32 yCenter, Int32 width, Int32 height, TrafficManager.Util.TwoDimLoopHandler handler)
   at TrafficManager.Manager.Impl.AdvancedParkingManager.FindParkingSpaceAtRoadSide(UInt16 ignoreParked, Vector3 refPos, Single width, Single length, Single maxDistance, Boolean randomize, Vector3 ByRef parkPos, Quaternion ByRef parkRot, Single ByRef parkOffset)
   at TrafficManager.Manager.Impl.AdvancedParkingManager.FindParkingSpaceInVicinity(Vector3 targetPos, .VehicleInfo vehicleInfo, UInt16 homeId, UInt16 vehicleId, Single maxDist, ExtParkingSpaceLocation ByRef parkingSpaceLocation, UInt16 ByRef parkingSpaceLocationId, Vector3 ByRef parkPos, Quaternion ByRef parkRot, Single ByRef parkOffset)
   at TrafficManager.Manager.Impl.AdvancedParkingManager.FindParkingSpaceForCitizen(Vector3 endPos, .VehicleInfo vehicleInfo, ExtCitizenInstance ByRef extDriverInstance, UInt16 homeId, Boolean goingHome, UInt16 vehicleId, Boolean allowTourists, Vector3 ByRef parkPos, Position ByRef endPathPos, Boolean ByRef calculateEndPos)
   at TrafficManager.Custom.AI.CustomCitizenAI.ExtStartPathFind(UInt16 instanceID, CitizenInstance ByRef instanceData, ExtCitizenInstance ByRef extInstance, ExtCitizen ByRef extCitizen, Vector3 startPos, Vector3 endPos, .VehicleInfo vehicleInfo, Boolean enableTransport, Boolean ignoreCost)
   at TrafficManager.Custom.AI.CustomCitizenAI.CustomStartPathFind(UInt16 instanceID, CitizenInstance ByRef citizenData, Vector3 startPos, Vector3 endPos, .VehicleInfo vehicleInfo, Boolean enableTransport, Boolean ignoreCost)
   at ResidentAI.StartPathFind(UInt16 instanceID, CitizenInstance ByRef citizenData)
   at ResidentAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetIndex, Boolean targetIsNode)
   at CitizenAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetBuilding)
   at OutsideConnectionAI.StartConnectionTransferImpl(UInt16 buildingID, Building ByRef data, TransferReason material, TransferOffer offer, Int32 touristFactor0, Int32 touristFactor1, Int32 touristFactor2)
   at OutsideConnectionAI.StartConnectionTransfer(UInt16 buildingID, Building ByRef data, TransferReason material, TransferOffer offer, Int32 touristFactor0, Int32 touristFactor1, Int32 touristFactor2)
   at OutsideConnectionAI.StartTransfer(UInt16 buildingID, Building ByRef data, TransferReason material, TransferOffer offer)
   at TransferManager.StartTransfer(TransferReason material, TransferOffer offerOut, TransferOffer offerIn, Int32 delta)
   at TransferManager.MatchOffers(TransferReason material)
   at TransferManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at TransferManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

**Comment by VictorPhilipp** [comment]
To make this savegame run I had to demolish all subway stations. Maybe I am missing some mod (MOM?).

**Comment by VictorPhilipp** [comment]
Just before the taxi vanishes:
![grafik](https://user-images.githubusercontent.com/4333935/59151297-f4b3d400-8a30-11e9-9a0c-9900f4b73a0c.png)

Path-finding fails because no valid end position can be found.
![grafik](https://user-images.githubusercontent.com/4333935/59151306-22008200-8a31-11e9-95df-d974fd378980.png)

**Comment by VictorPhilipp** [comment]
The savegame has become corrupt. Since the segment grid (translation between world point and road segment ids) is affected path-finding fails for certain positions.

**Comment by VictorPhilipp** [comment]
Your lane arrow are incorrectly set here:
![grafik](https://user-images.githubusercontent.com/4333935/59152195-b1149680-8a3f-11e9-9dbd-c055648beddf.png)

Correct would be:
![grafik](https://user-images.githubusercontent.com/4333935/59152203-cd183800-8a3f-11e9-9e99-29575bb0f38e.png)

That's the reason why taxis are unable to get to certain areas.

**Comment by VictorPhilipp** [comment]
![grafik](https://user-images.githubusercontent.com/4333935/59152216-18324b00-8a40-11e9-93a0-14553ea5f9fb.png)

This whole area is only reachable via the yellow road - and exactly there you can find the invalid lane arrows.

**Comment by VictorPhilipp** [comment]
Tagging #371, since old town policy is playing a major part in this issue

**Comment by aubergine10** [comment]
I forgot to test taxis back in April, doh! But I'm sure busses were working ok: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/167

**Comment by aubergine10** [comment]
From #391:

![60309724-943cf600-994f-11e9-942a-38909378b686](https://user-images.githubusercontent.com/1386719/60317060-416e3900-9965-11e9-97cf-dd700e5cbd43.png)

Orange lane = currently selected incoming lane. Green lanes = the lanes it connects to.
