### ISSUE TITLE
Possible missing translation keys

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#468]
EDIT: This was from 10.21.1 LABS edition of the mod

Just noticed these in a log posted to another issue:

```
[Warning] @ 4862064764 Translated file light_mode_ru.png not found!
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Warning(System.String s)
   at TrafficManager.UI.Translation.GetTranslatedFileName(System.String filename)
   at TrafficManager.UI.TextureResources..cctor()
   at TrafficManager.UI.UIMainMenuButton.Start()
   at TrafficManager.UI.UIMainMenuButton.Start()

[Warning] @ 4862127395 Translated file light_counter_ru.png not found!
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Warning(System.String s)
   at TrafficManager.UI.Translation.GetTranslatedFileName(System.String filename)
   at TrafficManager.UI.TextureResources..cctor()
   at TrafficManager.UI.UIMainMenuButton.Start()
   at TrafficManager.UI.UIMainMenuButton.Start()
```

Not sure what's going on there - does the translation system also translate image files?!

**Comment by kvakvs** [comment]
Traffic lights UI have text in them:
- `light_mode["", "_ja", "_pl"].png`
- `light_counter["", "_ja", "_pl"].png`

**Comment by aubergine10** [comment]
I assume that is likely to change once we get round to overhauling the traffic lights UI so closing this.
